# To be built using command:
# docker-compose up --no-recreate -d

# To be re-built using command:
# docker-compose up -d --build --no-recreate

# To start it again without building images using command:
# docker-compose up -d --no-build

version: '2.0'

services:
  # MySQL data container
  jeedom-data:
      build: ./jeedom-data
      container_name: jeedom-data
      image: cbresolin/rpi-jeedom-data:3.1

  # MySQL DB container#
  jeedom-mysql:
      depends_on:
          - jeedom-data
      container_name: jeedom-mysql
      image: hypriot/rpi-mysql
      restart: always
      environment:
          - MYSQL_ROOT_PASSWORD=mysqlroot
      volumes_from:
          - jeedom-data
      networks:
          pi_default:
            ipv4_address: 172.18.0.2

  # Jeedom container
  jeedom:
      build: ./jeedom
      depends_on:
          - jeedom-mysql
      container_name: jeedom
      image: cbresolin/rpi-jeedom:3.1
      restart: always
      ports:
          - 80:80     # http
          - 443:443   # https
          - 8083:8083 # Open zwave
      links:
          - jeedom-mysql:mysql
      mac_address: 02:42:1a:4a:5b:66
      devices:
          - /dev/ttyACM0:/dev/ttyACM0  # Zwave controller
          - /dev/rfcomm0:/dev/rfcomm0  # BT Arduino device
  # Avoid writing on SDCard to often (supported from docker-compose 1.7.1)
      tmpfs:
          - /tmp:rw,size=64M
          - /var/log:rw,size=32M
          - /usr/share/nginx/www/jeedom/log:rw,size=32M
