# To create & start services:
# docker-compose up -d

# To stop services:
# docker-compose stop

# To stop services & remove them:
# docker-compose down

version: '2.1'

services:
  # MySQL data container
  jeedom-data:
      build: ./jeedom-data
      container_name: jeedom-data
      image: cbresolin/rpi-jeedom-data:stable

  # MySQL DB container#
  jeedom-mysql:
      depends_on:
          - jeedom-data
      container_name: jeedom-mysql
      image: hypriot/rpi-mysql:latest
      restart: always
      environment:
          - MYSQL_ROOT_PASSWORD=mysqlroot
      volumes_from:
          - jeedom-data
      networks:
          default:
              ipv4_address: 172.18.0.2

  # Jeedom container
  jeedom:
      build: ./jeedom
      depends_on:
          - jeedom-mysql
      container_name: jeedom
      image: cbresolin/rpi-jeedom:stable
      restart: always
      ports:
          - 80:80     # http
          - 443:443   # https
          - 8083:8083 # Open zwave
      links:
          - jeedom-mysql:mysql
      mac_address: 02:42:1a:4a:5b:66
      devices:
          - /dev/ttyACM0:/dev/ttyACM0  # Zwave controller
          - /dev/rfcomm0:/dev/rfcomm0  # BT Arduino device
  # Avoid writing on SDCard to often (supported from docker-compose 1.7.1)
      tmpfs:
          - /tmp:rw,size=64M
          - /var/log:rw,size=32M
          - /usr/share/nginx/www/jeedom/log:rw,size=32M
      networks:
          default:
              ipv4_address: 172.18.0.3

networks:
    default:
        driver: bridge
        enable_ipv6: false
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1
