#!/bin/bash

# Wait a few seconds so crontab update will be taken into account
sleep 3

# Update crontab
echo "* * * * * www-data /usr/bin/php /var/www/html/core/php/jeeCron.php >> /dev/null" > /etc/cron.d/jeedom
