#!/bin/bash

# Create log folder. If it does not exist (can happen while using tmpfs) supervisord exits
mkdir -p /var/log/supervisor

# Nginx log foler
mkdir -p /var/log/nginx

# www-data needs write access to this folder
chmod a+w /var/www/html/log

# Start nginx
service php7.0-fpm start
service nginx start

/usr/bin/supervisord
