#!/bin/bash

# Create log folder. If it does not exist (can happen while using tmpfs) supervisord exits
mkdir -p /var/log/supervisor

# Nginx log foler
mkdir -p /var/log/nginx

# www-data needs write access to this folder
chmod a+w $WEBSERVER_HOME/log

/usr/bin/supervisord
